directories:
  output: release
  buildResources: build
appId: com.scribe.app
productName: Nexus
files:
  - filter:
      - '!src/**'
      - '!tests/**'
      - '!e2e/**'
      - '!**/*.map'
asarUnpack:
  - '**/*.node'
extraResources:
  - from: build/icon.png
    to: icon.png
npmRebuild: false
win:
  target:
    - nsis
  icon: build/icon.ico
  signAndEditExecutable: false
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  shortcutName: Nexus
  installerIcon: build/icon.ico
  uninstallerIcon: build/icon.ico
  installerHeaderIcon: build/icon.ico
publish:
  provider: generic
  url: https://nexus-web.vercel.app/api/updates/
electronVersion: 33.4.11
